/**
 * @fileoverview CreateUser use case - handles user creation business logic
 */

import { User } from '../entities/User.js';

/**
 * Result object returned by use case execution
 * @typedef {Object} UseCaseResult
 * @property {boolean} success - Whether the operation succeeded
 * @property {User|null} data - User entity if successful
 * @property {string|null} error - Error message if failed
 */

/**
 * CreateUser Use Case
 * 
 * @class
 * @classdesc Handles the business logic for creating new users in the system
 */
export class CreateUser {
  /**
   * Creates a new CreateUser use case instance
   * 
   * @param {Object} dependencies - Use case dependencies
   * @param {UserRepository} dependencies.userRepository - Repository for user data operations
   */
  constructor({ userRepository }) {
    /**
     * @type {UserRepository}
     * @private
     */
    this._userRepository = userRepository;

    if (!this._userRepository) {
      throw new Error('UserRepository is required');
    }
  }

  /**
   * Executes the user creation use case
   * 
   * @param {Object} userData - User data for creation
   * @param {string} userData.username - Username (required)
   * @param {string} userData.password - Password (required)
   * @param {string} [userData.email] - User email
   * @param {string} [userData.fullName] - User full name
   * @param {UserRole} [userData.role='user'] - User role
   * @param {string} [authHeader] - Optional authorization header for API requests
   * @returns {Promise<UseCaseResult>} Result object with success status and user data or error
   */
  async execute(userData, authHeader = null) {
    try {
      // Validate required fields
      if (!userData.username || !userData.password) {
        return {
          success: false,
          data: null,
          error: 'Username and password are required',
        };
      }

      // Validate username format (basic validation)
      if (userData.username.trim().length < 3) {
        return {
          success: false,
          data: null,
          error: 'Username must be at least 3 characters long',
        };
      }

      // Validate password strength (basic validation)
      if (userData.password.length < 6) {
        return {
          success: false,
          data: null,
          error: 'Password must be at least 6 characters long',
        };
      }

      // Create User entity instance
      // Using conditional property spreading (ES2022) to omit id if not provided
      // The id will be generated by the database/repository
      const user = new User({
        // Only include id if explicitly provided (for special cases like testing)
        ...(userData.id && { id: userData.id }),
        username: userData.username.trim(),
        password: userData.password,
        email: userData.email?.trim() ?? null,
        fullName: userData.fullName?.trim() ?? null,
        role: userData.role ?? 'user',
        isActive: userData.isActive ?? true,
      });

      // Persist user via repository
      // The repository will handle the id generation by the database
      const createdUser = await this._userRepository.createUser(user, authHeader);

      // Clear password from memory after creation for security
      createdUser.clearPassword();

      return {
        success: true,
        data: createdUser,
        error: null,
      };
    } catch (error) {
      // Handle repository errors
      return {
        success: false,
        data: null,
        error: error.message || 'Failed to create user',
      };
    }
  }
}

