/**
 * @fileoverview SignUp use case - handles user registration business logic
 */

import { User } from '../entities/User.js';

/**
 * Result object returned by use case execution
 * @typedef {Object} UseCaseResult
 * @property {boolean} success - Whether the operation succeeded
 * @property {User|null} data - User entity if successful
 * @property {string|null} error - Error message if failed
 */

/**
 * SignUp Use Case
 * 
 * @class
 * @classdesc Handles the business logic for user registration/signup in the system
 */
export class SignUp {
  /**
   * Creates a new SignUp use case instance
   * 
   * @param {Object} dependencies - Use case dependencies
   * @param {UserRepository} dependencies.userRepository - Repository for user data operations
   */
  constructor({ userRepository }) {
    /**
     * @type {UserRepository}
     * @private
     */
    this._userRepository = userRepository;

    if (!this._userRepository) {
      throw new Error('UserRepository is required');
    }
  }

  /**
   * Validates email format
   * 
   * @param {string} email - Email to validate
   * @returns {boolean} True if email format is valid
   * @private
   */
  _isValidEmail(email) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  /**
   * Validates password strength
   * 
   * @param {string} password - Password to validate
   * @returns {Object} Validation result with isValid flag and error message
   * @private
   */
  _validatePassword(password) {
    if (password.length < 6) {
      return {
        isValid: false,
        error: 'Password must be at least 6 characters long',
      };
    }
    return { isValid: true, error: null };
  }

  /**
   * Executes the signup use case
   * 
   * @param {Object} userData - User data for registration
   * @param {string} userData.email - User email (required)
   * @param {string} userData.password - Password (required)
   * @param {string} [userData.fullName] - User full name
   * @param {string} [userData.username] - Username (optional, defaults to email if not provided)
   * @param {string} [authHeader] - Optional authorization header for API requests
   * @returns {Promise<UseCaseResult>} Result object with success status and user data or error
   */
  async execute(userData, authHeader = null) {
    try {
      // Validate required fields
      if (!userData.email || !userData.password) {
        return {
          success: false,
          data: null,
          error: 'Email and password are required',
        };
      }

      // Validate email format
      if (!this._isValidEmail(userData.email.trim())) {
        return {
          success: false,
          data: null,
          error: 'Please enter a valid email address',
        };
      }

      // Validate password strength
      const passwordValidation = this._validatePassword(userData.password);
      if (!passwordValidation.isValid) {
        return {
          success: false,
          data: null,
          error: passwordValidation.error,
        };
      }

      // Use email as username if username is not provided
      const username = userData.username?.trim() || userData.email.trim();

      // Create User entity instance
      // The id will be generated by Supabase after authentication
      const user = new User({
        username: username,
        password: userData.password,
        email: userData.email.trim(),
        fullName: userData.fullName?.trim() ?? null,
        role: userData.role ?? 'user',
        isActive: true,
      });

      // Persist user via repository
      // The repository will handle the authentication and id generation
      const createdUser = await this._userRepository.createUser(user, authHeader);

      // Clear password from memory after creation for security
      if (createdUser) {
        createdUser.clearPassword();
      }

      return {
        success: true,
        data: createdUser,
        error: null,
      };
    } catch (error) {
      // Handle repository errors
      return {
        success: false,
        data: null,
        error: error.message || 'Failed to sign up',
      };
    }
  }
}

