/**
 * @fileoverview User entity representing an authenticated user in the system
 */

/**
 * User roles in the system
 * @typedef {'admin'|'user'|'guest'} UserRole
 */

/**
 * User entity class
 * 
 * @class
 * @classdesc Represents a user in the Avecta AI system with authentication credentials
 * and profile information
 */
export class User {
  /**
   * Creates a new User instance
   * 
   * @param {Object} params - User initialization parameters
   * @param {string} [params.id] - Unique identifier for the user (optional, will be generated by database)
   * @param {string} params.username - Username for authentication
   * @param {string} [params.password] - Password (optional, should not be stored in memory after auth)
   * @param {string} [params.email] - User's email address
   * @param {string} [params.fullName] - User's full name
   * @param {UserRole} [params.role='user'] - User's role in the system
   * @param {Date} [params.createdAt] - Account creation date
   * @param {Date} [params.lastLoginAt] - Last login timestamp
   * @param {boolean} [params.isActive=true] - Whether the user account is active
   */
  constructor({
    id = null,
    username,
    password = null,
    email = null,
    fullName = null,
    role = 'user',
    createdAt = null,
    lastLoginAt = null,
    isActive = true,
  }) {
    /**
     * @type {string|null}
     * @readonly
     */
    this.id = id;

    /**
     * @type {string}
     */
    this.username = username;

    /**
     * @type {string|null}
     * @private
     */
    this._password = password;

    /**
     * @type {string|null}
     */
    this.email = email;

    /**
     * @type {string|null}
     */
    this.fullName = fullName;

    /**
     * @type {UserRole}
     */
    this.role = role;

    /**
     * @type {Date|null}
     * @readonly
     */
    this.createdAt = createdAt || new Date();

    /**
     * @type {Date|null}
     */
    this.lastLoginAt = lastLoginAt;

    /**
     * @type {boolean}
     */
    this.isActive = isActive;
  }

  /**
   * Gets the password for authentication purposes
   * This method should only be used by repositories during user creation/authentication
   * 
   * @returns {string|null} The password or null if not available
   */
  getPassword() {
    return this._password;
  }

  /**
   * Generates Basic Auth header for API requests
   * 
   * @returns {string|null} Basic auth header string or null if password not available
   */
  getAuthHeader() {
    if (!this.username || !this._password) {
      return null;
    }
    return `Basic ${btoa(`${this.username}:${this._password}`)}`;
  }

  /**
   * Clears sensitive password data from memory
   * Should be called after authentication
   * 
   * @returns {void}
   */
  clearPassword() {
    this._password = null;
  }

  /**
   * Updates the last login timestamp
   * 
   * @returns {void}
   */
  updateLastLogin() {
    this.lastLoginAt = new Date();
  }

  /**
   * Checks if user has admin privileges
   * 
   * @returns {boolean}
   */
  isAdmin() {
    return this.role === 'admin';
  }

  /**
   * Checks if user account is active
   * 
   * @returns {boolean}
   */
  isAccountActive() {
    return this.isActive;
  }

  /**
   * Creates a User instance from a plain object
   * Useful for deserializing from API responses or localStorage
   * 
   * @param {Object} data - Plain object with user data
   * @returns {User}
   * @static
   */
  static fromObject(data) {
    return new User({
      // Only include id if present (database-generated)
      ...(data.id && { id: data.id }),
      username: data.username,
      email: data.email,
      fullName: data.fullName,
      role: data.role || 'user',
      createdAt: data.createdAt ? new Date(data.createdAt) : null,
      lastLoginAt: data.lastLoginAt ? new Date(data.lastLoginAt) : null,
      isActive: data.isActive !== undefined ? data.isActive : true,
    });
  }

  /**
   * Converts User instance to a plain object
   * Excludes sensitive data like password
   * Useful for serialization to API or localStorage
   * 
   * @returns {Object}
   */
  toObject() {
    // Using conditional property spreading to omit id if null/undefined
    return {
      ...(this.id && { id: this.id }),
      username: this.username,
      email: this.email,
      fullName: this.fullName,
      role: this.role,
      createdAt: this.createdAt?.toISOString() || null,
      lastLoginAt: this.lastLoginAt?.toISOString() || null,
      isActive: this.isActive,
    };
  }

  /**
   * Creates a safe copy of user data for display
   * Removes all sensitive information
   * 
   * @returns {Object}
   */
  toSafeObject() {
    const obj = this.toObject();
    delete obj._password;
    return obj;
  }
}

