/**
 * @fileoverview User Repository interface for data persistence operations
 */

import { User } from '../entities/User.js';

/**
 * User Repository interface
 * 
 * @interface
 * @classdesc Defines the contract for user data persistence operations
 */
export class UserRepository {
  /**
   * Creates a new user in the system
   * 
   * @param {User} user - User entity to create (without id, as it will be generated by the database)
   * @param {string} [authHeader] - Optional authorization header for API requests
   * @returns {Promise<User>} The created user entity with server-generated id
   * @throws {Error} If user creation fails
   */
  async createUser(user, authHeader = null) {
    throw new Error('createUser() must be implemented by concrete repository');
  }

  /**
   * Finds a user by ID
   * 
   * @param {string} id - User ID
   * @param {string} [authHeader] - Optional authorization header
   * @returns {Promise<User|null>} User entity or null if not found
   */
  async findById(id, authHeader = null) {
    throw new Error('findById() must be implemented by concrete repository');
  }

  /**
   * Finds a user by username
   * 
   * @param {string} username - Username to search for
   * @param {string} [authHeader] - Optional authorization header
   * @returns {Promise<User|null>} User entity or null if not found
   */
  async findByUsername(username, authHeader = null) {
    throw new Error('findByUsername() must be implemented by concrete repository');
  }

  /**
   * Updates an existing user
   * 
   * @param {User} user - User entity with updated data (must include id)
   * @param {string} [authHeader] - Optional authorization header
   * @returns {Promise<User>} Updated user entity
   */
  async updateUser(user, authHeader = null) {
    throw new Error('updateUser() must be implemented by concrete repository');
  }

  /**
   * Deletes a user by ID
   * 
   * @param {string} id - User ID to delete
   * @param {string} [authHeader] - Optional authorization header
   * @returns {Promise<boolean>} True if deletion was successful
   */
  async deleteUser(id, authHeader = null) {
    throw new Error('deleteUser() must be implemented by concrete repository');
  }

  /**
   * Authenticates a user with email and password
   * 
   * @param {string} email - User email
   * @param {string} password - User password
   * @returns {Promise<User|null>} User entity if authentication succeeds, null otherwise
   * @throws {Error} If authentication fails
   */
  async authenticate(email, password) {
    throw new Error('authenticate() must be implemented by concrete repository');
  }
}

